PREFIX vph: <http://www.zinl.nl/ontologies/VPH-domain-ontology#>
PREFIX kik: <https://purl.org/ozo/kik#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?type_contract (COUNT(?c) AS ?aantal)

WHERE {
    ?tc rdfs:subClassOf kik:WerkOvereenkomst .
    ?tc rdfs:label ?type_contract .
    ?c a ?tc .
}
group by ?type_contract
